const projectDescriptions = [
  "An interactive tool that estimates the energy consumption and CO₂ emissions generated by using AI models. Users input the number of prompts, message length, and model type, and receive clear environmental impact results, including real-world equivalents like kilometers driven or trees needed to offset emissions.",
  "A machine learning project implementing Linear and Logistic Regression models from scratch in TypeScript. It predicts continuous values like housing prices and classifies outcomes such as customer purchase behavior, demonstrating core predictive modeling techniques.",
];

export const projects = [
  {
    id: "1",
    name: "AI Carbon Calculator",
    description: projectDescriptions[0],
    href: "https://github.com/pietrodev07/ai-carbon-calculator",
    dates: "2025 - Present",
  },
  {
    id: "2",
    name: "Regressions",
    description: projectDescriptions[1],
    href: "https://github.com/pietrodev07/regressions",
    dates: "2025 - Present",
  },
];
