const projectDescriptions = [
  "A full-stack web application that uses AI to translate tweets into a wide range of creative writing styles while preserving their original meaning. Users input any tweet or short message and choose from a list of styles—such as Gen-Z slang, Shakespearean English, Corporate jargon, Pirate speak, Sigma Male tone, or Academic formalism.",
  "An interactive tool that estimates the energy consumption and CO₂ emissions generated by using AI models. Users input the number of prompts, message length, and model type, and receive clear environmental impact results, including real-world equivalents like kilometers driven or trees needed to offset emissions.",
  "A machine learning project implementing Linear and Logistic Regression models from scratch in TypeScript. It predicts continuous values like housing prices and classifies outcomes such as customer purchase behavior, demonstrating core predictive modeling techniques.",
];

export const projects = [
  {
    id: "1",
    name: "Twift - Ai Tweet Translator",
    description: projectDescriptions[0],
    href: "https://github.com/pietrodev07/twift-app",
    dates: "2025 - Present",
  },
  {
    id: "2",
    name: "CarbonAI - Ai Carbon Calculator",
    description: projectDescriptions[1],
    href: "https://github.com/pietrodev07/carbonai-calculator",
    dates: "2025 - Present",
  },
  {
    id: "3",
    name: "Regressions - Machine Learning Kit",
    description: projectDescriptions[2],
    href: "https://github.com/pietrodev07/regressions",
    dates: "2025 - Present",
  },
];
