import { Metadata } from "next";

export const metadataLib: Metadata = {
  title: "pietrodev07",
  description: "17 years old full-stack developer",
  metadataBase: new URL("https://pietrodev07.vercel.app"),
  openGraph: {
    type: "website",
    locale: "en_US",
    images: [{ url: "/open-graph-image.png" }],
    title: "pietrodev07 - 17 years old full-stack developer",
    description: "pietrodev07 - 17 years old full-stack developer",
  },
  twitter: {
    images: [{ url: "/open-graph-image.png" }],
    title: "pietrodev07 - 17 years old full-stack developer",
    description: "pietrodev07 - 17 years old full-stack developer",
  },
  keywords: [
    "pietrodev07",
    "full-stack developer",
    "software engineer",
    "software developer",
    "software engineering",
    "web developer",
    "web development",
    "frontend developer",
    "frontend development",
    "backend developer",
    "backend development",
    "fullstack developer",
    "fullstack development",
    "javascript developer",
    "javascript development",
    "typescript developer",
    "typescript development",
    "reactjs developer",
    "reactjs development",
    "nextjs developer",
    "nextjs development",
  ],
};
